### ISSUE TITLE
bug: first submission assumes factor is 1x

### ISSUE THREAD

**Issue by particle** [taustation-fan/career-task-tracker#8]
my first submission yields to my eyes what appears to be higher than baseline career payouts, yet the script reports 1x. it is unknown (to me) how this will affect career payout reporting in the future me.

**Comment by moritz** [comment]
@particle I'm afraid this is unavailable when the tasks haven't been seen before by the script.

In each submit, the tasks's baseline is set to the minimum of all the values that have been seen so far, so subsequent submits should fix it.
